// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "MoveIntake.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

MoveIntake::MoveIntake() : Subsystem("MoveIntake") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    doubleSolenoid1 = RobotMap::moveIntakeDoubleSolenoid1;
    doubleSolenoid2 = RobotMap::moveIntakeDoubleSolenoid2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    IntakeState = true;
}

void MoveIntake::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void MoveIntake::UpIntake()
{
	RobotMap::moveIntakeDoubleSolenoid1->Set(frc::DoubleSolenoid::kForward);
	RobotMap::moveIntakeDoubleSolenoid2->Set(frc::DoubleSolenoid::kForward);
	IntakeState = true;
}

void MoveIntake::DownIntake()
{
	RobotMap::moveIntakeDoubleSolenoid1->Set(frc::DoubleSolenoid::kReverse);
	RobotMap::moveIntakeDoubleSolenoid2->Set(frc::DoubleSolenoid::kReverse);
	IntakeState = false;
}
